import Navbar from "../components/navbar/Navbar";
import { ProviderRedux } from "../redux/provider";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Glamify - Tu Destino para la Moda",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ProviderRedux>
          <Navbar />
          {children}
        </ProviderRedux>
      </body>
    </html>
  );
}
